### ISSUE TITLE
JS-less sticky header

### ISSUE THREAD

**Issue by webknjaz** [bluebirrd/nau-timetable#5]
Working example:

``` css
.block__hero {
    position: relative;
    z-index: 2;
}
.nav-panel {
    z-index: 2;
}
.nav-panel:first-of-type {
    position: fixed;
    top: 0;
    width: 100%;
}
```
